baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Future Forge'
theme = 'ananke'






[params]
text_color = "bg black"
author = "Future Forge team"
favicon = ""
site_logo = ""
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-red"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center pa4 justify-center f8"
#featured_image_class = "cover bg-center f4"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg white"
recent_posts_number = 1




[params.ananke.social.follow]
networks = [
  "facebook",
  "instagram"
]

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/AudiSport/"

[params.ananke.social.instagram]
profilelink = "https://www.instagram.com/audi/"
